[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api-redash/*"
  to = "/.netlify/functions/proxy"
  status = 200
  force = true

[[redirects]]
  from = "/api-recebimento/product"
  to = "/.netlify/functions/recebimento-product"
  status = 200
  force = true

[[redirects]]
  from = "/api-check-user"
  to = "/.netlify/functions/check-user"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
