[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  [build.environment]
    HUSKY = "0"

[dev]
  command = "node ./node_modules/vite/bin/vite.js --host 127.0.0.1 --port 5173"
  targetPort = 5173
  port = 8888

[[redirects]]
  from = "/api-redash/*"
  to = "/.netlify/functions/proxy"
  status = 200
  force = true

[[redirects]]
  from = "/api-recebimento/product"
  to = "/.netlify/functions/recebimento-product"
  status = 200
  force = true

[[redirects]]
  from = "/api-check-user"
  to = "/.netlify/functions/check-user"
  status = 200
  force = true

[[redirects]]
  from = "/api-bet-user-inf"
  to = "/.netlify/functions/bet-user-inf"
  status = 200
  force = true

[[redirects]]
  from = "/get_user_inf"
  to = "/.netlify/functions/get-user-inf"
  status = 200
  force = true

[[redirects]]
  from = "/get_produto_cadastro"
  to = "/.netlify/functions/get-produto-cadastro"
  status = 200
  force = true

[[redirects]]
  from = "/consulta_cnpj"
  to = "/.netlify/functions/consulta-cnpj"
  status = 200
  force = true

[[redirects]]
  from = "/salvar-orcamento"
  to = "/.netlify/functions/salvar-orcamento"
  status = 200
  force = true

[[redirects]]
  from = "/sync_orcamento_supabase"
  to = "/.netlify/functions/sync-orcamento-supabase"
  status = 200
  force = true

[[redirects]]
  from = "/update_valores"
  to = "/.netlify/functions/lancar-valores-orcamento"
  status = 200
  force = true

[[redirects]]
  from = "/get_orcamentos_analise"
  to = "/.netlify/functions/get-orcamentos-analise"
  status = 200
  force = true

[[redirects]]
  from = "/register_posto"
  to = "/.netlify/functions/register-posto"
  status = 200
  force = true

[[redirects]]
  from = "/post_orcamento_final"
  to = "/.netlify/functions/post-orcamento-final"
  status = 200
  force = true

[[redirects]]
  from = "/get_envios"
  to = "/.netlify/functions/get-envios"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
